apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: visionary-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: visionaryanalytics-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configuracoes-aplicacao
          env:
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: credenciais-principais
                  key: mongo-connection-string
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: credenciais-principais
                  key: rabbitmq-username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: credenciais-principais
                  key: rabbitmq-password
            - name: NotificacoesTempoReal__UrlHub
              value: ""
          volumeMounts:
            - name: armazenamento-videos
              mountPath: /app/uploads
      volumes:
        - name: armazenamento-videos
          persistentVolumeClaim:
            claimName: pvc-video-storage
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: visionary-analytics
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
