apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: visionary-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credenciais-principais
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credenciais-principais
                  key: mongo-root-password
          volumeMounts:
            - name: dados-mongo
              mountPath: /data/db
      volumes:
        - name: dados-mongo
          persistentVolumeClaim:
            claimName: pvc-mongo-dados
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: visionary-analytics
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  namespace: visionary-analytics
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017
  type: NodePort
