apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-video-storage
  namespace: visionary-analytics
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-dados
  namespace: visionary-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
